### ISSUE TITLE
卡在地图加载这一步

### ISSUE THREAD

**Issue by LongLiveForFreedom** [JimmyLing233/Github-Student-Certification-Guide#2]
目前停滞在地图加载这一步骤，即便打开bing.com再挂代理仍然无法加载

**Comment by JimmyLing233** [comment]
那只能尝试挂全局代理或者将原先申请表单关闭重新申请试试了（有概率不需要选择地图）。因为在国内bing会跳转到cn.bing.com的国区bing，而GIthub用的地图是海外的，您可以多尝试几次试试。

**Comment by LongLiveForFreedom** [comment]
> 那只能尝试挂全局代理或者将原先申请表单关闭重新申请试试了（有概率不需要选择地图）。因为在国内bing会跳转到cn.bing.com的国区bing，而GIthub用的地图是海外的，您可以多尝试几次试试。

谢谢回复。我尝试了好多次几乎都需要地图，也不知道是什么情况，代理我一直是挂全局。实在不行我去咸鱼几十块找人做了

**Comment by LongLiveForFreedom** [comment]
> 那只能尝试挂全局代理或者将原先申请表单关闭重新申请试试了（有概率不需要选择地图）。因为在国内bing会跳转到cn.bing.com的国区bing，而GIthub用的地图是海外的，您可以多尝试几次试试。

使用教育邮箱，再拍个学生证的照片直接就通过了，之前不用教育邮箱就会跳选择地图的界面，还是教育邮箱方便，几分钟搞定

**Comment by JimmyLing233** [comment]
> > 那只能尝试挂全局代理或者将原先申请表单关闭重新申请试试了（有概率不需要选择地图）。因为在国内bing会跳转到cn.bing.com的国区bing，而GIthub用的地图是海外的，您可以多尝试几次试试。
> 
> 使用教育邮箱，再拍个学生证的照片直接就通过了，之前不用教育邮箱就会跳选择地图的界面，还是教育邮箱方便，几分钟搞定

是这样的，使用教育邮箱的话审核程序都很便捷，核发认证也很迅速。
